# =========================
# PORTA E PATH CONFIG
# =========================
quarkus.http.port=8080
# Adiciona o prefixo /api em todos os endpoints do backend para funcionar com o proxy
quarkus.http.root-path=/api

# =========================
# BANCO DE DADOS (MySQL)
# =========================
quarkus.datasource.db-kind=mysql
quarkus.datasource.username=root
quarkus.datasource.password=1234
quarkus.datasource.jdbc.url=jdbc:mysql://localhost:3306/moeda_estudantil

# =========================
# HIBERNATE ORM
# =========================
quarkus.hibernate-orm.schema-management.strategy=update
quarkus.hibernate-orm.log.sql=true

# =========================
# CORS (Configuração Nativa)
# =========================
quarkus.http.cors=true
quarkus.http.cors.origins=http://localhost:4200
quarkus.http.cors.methods=GET,POST,PUT,DELETE,OPTIONS
quarkus.http.cors.headers=accept,authorization,content-type,x-requested-with
quarkus.http.cors.credentials=true